export const INSERT_USER_SUCCESS = 'INSERT_USER_SUCCESS';
export const INSERT_USER_FAILURE = 'INSERT_USER_FAILURE';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
